version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=${dbhost}
      - GITEA__database__NAME=git
      - GITEA__database__USER=${dbuser}
      - GITEA__database__PASSWD=${dbpass}
    # restart: always
    networks:
      - gitea
    volumes:
      - /mnt/nas/shared/Network/Mainframe/git:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3003:3000"
      - "222:22"

